#  created via the installer, mountpoint and all
#  including label, and everything, but it leaves everything uuid-ified :(

- name: de-uuidify /home in /etc/fstab - use labels for /home
  lineinfile:
    path: /etc/fstab
    backrefs: yes
    regexp: '^(UUID=.*\s+/home\s+)(.*)'
    line: 'LABEL=home	/home		\2'
