#  created via the installer, mountpoint and all
#  including label, and everything, but it leaves everything uuid-ified :(

- name: de-uuidify /etc/fstab - use labels for rootfs
  lineinfile:
    path: /etc/fstab
    backrefs: yes
    regexp: '^(UUID=.*\s+/\s+)(.*)'
    line: 'LABEL=root	/		\2'
