- name: Add bazel repo
  shell: echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list

- name: Adding bazel key
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    state: present

- name: Install bazel
  apt: pkg={{item}} state=present update-cache=yes force=yes 
  with_items:
    - bazel