- name: Append to fstab 
  mount:
    name: /work
    src: "thumper:/export/work"
    path: /etc/fstab
    fstype: nfs
    state: present   
    
    #thumper:/export/work /work nfs vers=3   0 0

- name: Create work directory
  file:
    path: '/work'
    state: directory
    mode: 0700 