- name: Get G++ repos
  apt_repository:
    repo: 'ppa:ubuntu-toolchain-r/test'
    state: present
    update_cache: yes
- name: G++ compilers
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - g++ 
    - cpp-doc
    - g++-5 
    - cpp-5-doc 
    - g++-6 
    - cpp-6-doc
    - g++-7 
    - cpp-7-doc