- name: create key directory
  file:
    path: /usr/.ssh/
    state: directory
    mode: 0700 
    recurse: yes
    
- name: Create authorized_keys
  file: 
    path: /usr/.ssh/authorized_keys
    state: touch
    mode: 0600
- name: Make users
    user: name={{item.name}}
    with_items: "{{ssh_users}}"

- name: create authorized_key for user accounts
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    state: present
    path: /usr/.ssh/authorized_keys
  with_items: "{{ ssh_users }}"