- name: Python general
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
    force: yes
  with_items:
    - python-dev
    - python3-dev
    - python-stdeb
    - python3-stdeb
    - python-nose
    - python3-nose

- name: Python analysis
  apt:
    pkg:  "{{ item }}"
    state: present
    update-cache: yes
    force: yes
  with_items:
    - python-numpy
    - python3-numpy
    - python-numpy-doc
    - python-scipy
    - python3-scipy
    - python-scipy-doc
    - python-matplotlib
    - python3-matplotlib
    - python-matplotlib-data
    - python-matplotlib-venn
    - python-matplotlib-doc
    - python-scitools

- name: Python AWS
  apt:
    pkg:  "{{ item }}"
    state: present
    update-cache: yes
    force: yes
  with_items:
    - aws-status
    - awscli
    - s3cmd

- name: Python Virtualenv
  apt:
    pkg: virtualenv
    state: present
    update-cache: yes
    force: yes
