- name: ray dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
    force: yes
  with_items:
    - libboost-all-dev
    - python-dev
    - python3-dev
    - python-numpy
    - python3-numpy
    - python-funcsigs
    - python3-funcsigs
    - flex
    - bison

- name: ray tune dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
    force: yes
  with_items:
    - libsox-fmt-mp3
