- name: riscv dev requirements
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
    force: yes
  with_items:
    - autoconf
    - automake
    - autotools-dev
    - curl
    - libmpc-dev
    - libmpfr-dev
    - libgmp-dev
    - libusb-1.0-0-dev
    - gawk
    - build-essential
    - bison
    - flex
    - texinfo
    - gperf
    - libtool
    - patchutils
    - bc
    - zlib1g-dev
    - device-tree-compiler
    - pkg-config
    - chrpath
    - diffstat
