- name: le-vert hardware raid tools repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 6005210E23B3D3B4
    state: present

- name: le-vert hardware raid tools repo
  apt_repository:
    repo: "deb http://hwraid.le-vert.net/ubuntu xenial main"

- name: useful system utilities
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
    force: yes
    install_recommends: no
  with_items:
    - megacli
    - bridge-utils
    - sysstat
    - partimage
    - debirf
    - apt-file
    - dump
    - lxc
    - cgroup-bin
    - dkms
    - hugepages
    - cryptsetup
    - cpu-checker
    - linux-tools-common
    - hwloc
    - htop
    - build-essential
    - build-essential
    - nmap
    - xfsprogs
    - xfsdump
    - attr
    - quota
    - udftools
    - ipmitool
    - numactl
    - tree
