- name: TensorFlow build dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
    force: yes
  with_items:
    - git
    # - bazel
    # handled via bazel task
    # - cuda-whatever
    # handled on GPU systems via the CUDA tasks
    - python-numpy
    - python-dev
    - python-pip
    - python-wheel
    - python3-numpy
    - python3-dev
    - python3-pip
    - python3-wheel
