- name: cuda repo
  apt:
    deb: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.2.148-1_amd64.deb
    update_cache: yes

- name: cuda repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7FA2AF80
    state: present

- name: cuda 9.2 cuda-9.1 cuda-9.0 and cuda-8-0 without all the extra cruft
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
    force: yes
    install_recommends: no
  with_items:
    - cuda
    - cuda-9-1
    - cuda-9-0
    - cuda-8-0

- name: our gpustat deb
  apt:
    deb: "{{ item }}"
    state: present
    update-cache: yes
    force: yes
    install_recommends: no
  with_items:
    - https://research.eecs.berkeley.edu/pkgs/python-gpustat_0.3.2-1_all.deb

- name: our gpuwatch wrapper
  lineinfile:
    path: /usr/bin/gpuwatch
    line: watch -ctn 1 gpustat -cup
    state: present
    create: yes
    mode: 0555
