- name: udev rules for havoc ethernet device naming
  copy:
    src: 70-persistent-net.rules-havoc
    dest: /etc/udev/rules.d/70-persistent-net.rules

- name: havoc network interface config
  copy:
    dest: /etc/network/interfaces
    src: interfaces-havoc
