- name: S2600WT systems rules
  lineinfile:
    path: /etc/udev/rules.d/70-persistent-net.rules
    line: "{{item}}"
    with_items:
      - "ACTION=='add', SUBSYSTEM=='net', DRIVERS=='ixgbe', KERNELS=='0000:81:00.0', NAME='ixgbem0'"
      - "ACTION=='add', SUBSYSTEM=='net', DRIVERS=='ixgbe', KERNELS=='0000:81:00.1', NAME='ixgbem1'"
      - "ACTION=='add', SUBSYSTEM=='net', DRIVERS=='i40e', KERNELS=='0000:82:00.0', NAME='i10e0'"
      - "ACTION=='add', SUBSYSTEM=='net', DRIVERS=='i40e', KERNELS=='0000:82:00.1', NAME='i10e1'"
      - "ACTION=='add', SUBSYSTEM=='net', DRIVERS=='i40e', KERNELS=='0000:82:00.2', NAME='i10e2'"
      - "ACTION=='add', SUBSYSTEM=='net', DRIVERS=='i40e', KERNELS=='0000:82:00.3', NAME='i10e3'"

- name: Network interface
  lineinfile:
    path: /etc/network/interfaces
    line: "{{item}}"
    with_items:
      - "auto lo"
      - "iface lo inet loopback"
      - "auto ixgbem0"
      - "iface ixgbem0 inet dhcp"
      - "auto enp129s0f0"
      - "iface enp129s0f0 inet dhcp"
      - "auto eth0"
      - "iface eth0 inet dhcp"
